### ISSUE TITLE
Where does the duration for a new timer come from?

### ISSUE THREAD

**Issue by geekytime** [geekytime/cronlab#2]
I'm guessing that the duration is determined by the "test type" and "test method", and should be set as part of the same metadata that fills those drop-downs, but I wasn't sure, so I'm just defaulting them all to 1:30 for the sake of discussion.

**Comment by kevinsub1** [comment]
You are correct. The times for the most part don't change unless it is a special user defined test. Each type of test has a normal interval that will need to be defined under the Admin account to set the standard countdown time for predefined tests. In the case of a special user defined test they will have to set the interval. I don't currently have those times but we can get them. For the sake of development 1:30 is fine.

**Comment by geekytime** [comment]
These are pulling from the data file as of 665f3a641cb0351776899a9f848f9a92b3041062
