### ISSUE TITLE
Ensure timers still have a color when they hit zero

### ISSUE THREAD

**Issue by geekytime** [geekytime/cronlab#23]
As reported by @kevinsub1:

The timer should be yellow during the allowance time before it hits zero, and then yellow flashing after it hits zero, but before the allowance time runs out.

**Comment by kevinsub1** [comment]
Great



Sent from my Verizon 4G LTE smartphone


-------- Original message --------

**Comment by geekytime** [comment]
This should be fixed in 836206587e70cb78ed25aafa0028f6869ad176ea.

I designated the timer states as:

- waiting: remaining still above allowance time
- ready: remaining time within allowance time
- warning: remaining time less than 0, but still within allowance time
- expired: remaining time is negative and less than negative allowance time

The colors are all set in the style sheets based on these four states, so it'd be really easy to change the colors and flashing, if we decide we want a new color scheme based on these same states.
